### ISSUE TITLE
cannot delegate capability index/* error

### ISSUE THREAD

**Issue by tomohiro-n** [storacha-network/w3cli#199]
With `@web3-storage/w3cli@7.8.1`, the below command failed.
I've downgraded to 7.6.2 and it worked.

```
$ w3 delegation create <replace_this_by_did> --base64
file:///Users/tomohiro/.config/yarn/global/node_modules/@web3-storage/access/dist/src/agent.js:379
                throw new Error(`cannot delegate capability ${cap.can} with ${cap.with}`);
                      ^

Error: cannot delegate capability index/* with <replace_this_by_did>
    at Agent.delegate (file:///Users/tomohiro/.config/yarn/global/node_modules/@web3-storage/access/dist/src/agent.js:379:23)
    at Client.createDelegation (file:///Users/tomohiro/.config/yarn/global/node_modules/@web3-storage/w3up-client/dist/src/client.js:262:52)
    at createDelegation (file:///Users/tomohiro/.config/yarn/global/node_modules/@web3-storage/w3cli/index.js:402:35)
```

**Comment by tomohiro-n** [comment]
This error is gone after I reset and did everything with v7.8.1. Closing for now.
